### PR TITLE
User can use 1Password to fill in their credentials

### PR DESCRIPTION
**Pull request by jtrespalacios**
### Summary

Adds 1Password integration for login.

### CODE REVIEW

**Comment by reneklacan** [comment]
👍 oh nice, thank you for contribution!

**Comment by jacortinas** [comment]
@jtrespalacios Awesome! Testing it out. 💃

**Comment by jtrespalacios** [comment]
No problem, glad to help out.  Is the app only going to be for messaging or are there plans to add in groups and events as well?  Would love to help build it out some.

**Comment by alias1** [comment]
I really hope events.. That's the part I am most keen to see!

Get Outlook for iOS




On Fri, Aug 5, 2016 at 3:40 AM +1000, "Jeff Trespalacios" <notifications@github.com> wrote:












No problem, glad to help out.  Is the app only going to be for messaging or are there plans to add in groups and events as well?  Would love to help build it out some.

**Pull request closed without merging**
