### PR TITLE
Added more info to profile view

### PR DESCRIPTION
**Pull request by whitehat007**
## Full Changes:
* Added checks for Realm write transactions (this should fix the crash caused when tapping a conversation while updating)
* Added icon for FetLife supporter
* Improved parsing of JSON strings to preserve line breaks
* Added unread conversation count indicator in mailbox switching control
* Added method to update profile view if additional info wasn't fully loaded when the view is presented

### CODE REVIEW

**Comment by reneklacan** [comment]
Thank you!

**Comment by Adam24** [comment]
is there a pre compiled version of this update available? I successfully installed the one @whitehat007 gave me. wondering if that's the latest build.

**Comment by Adam24** [comment]
@whitehat007 installation.cpp:42
Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.vUGdzQ/extracted/Payload/FetLife.app : 0xe8008016 (The executable was signed with invalid entitlements.)

**Comment by Adam24** [comment]
old version works fine.

**Comment by whitehat007** [comment]
Try this: 
[FetLife.ipa.zip](https://github.com/fetlife/ios/files/2207206/FetLife.ipa.zip)

**Comment by Adam24** [comment]
@whitehat007 that one works! is it normal for the profile photos to show a ? instead of the photo?

**Comment by ClioCJS** [comment]
I tried really hard to install that one with windows :)  Unzipped the IPA, added my device ID to the list, then used Diawi.com to sideload it, but alas, the download within Diawi failed.. I'm really stubborn. I don't have a mac.  I wish this could be put on  one of the 3rd party app stores. I know a ton of people less smart than me who definitely can't figure this out :)

**Comment by whitehat007** [comment]
@Adam24 Unfortunately, yes--there's a bug with the API that prevents profile pictures from showing up 😢 
@ClioCJS It might be because I don't have your UDID added to the provisioning profile. I can try adding it manually, but it still might not work. You can get your UDID by tapping this: 
image from this link: https://i.diawi.com/Kp2EdK

**Pull request merged**
